
#!/usr/bin/env python3
"""
arcgis_bridge.py v2 — Bridge between ArcGIS pipeline and SageMaker training

Reads port_risk_data.json (generated by run_pipeline.py from live ArcGIS
PPQ Feature Layers) and produces arcgis_enrichment.csv for the ML pipeline.

KEY: The ArcGIS detections layer uses COUNTY NAMES, but Final.csv uses
AIRPORT CODES. This script maps counties → nearest major airport and
aggregates multi-county data per airport per month.

Usage:
    python arcgis_bridge.py                  # local port_risk_data.json
    python arcgis_bridge.py --upload         # also upload to S3
"""

import json
import os
import argparse
import pandas as pd
import numpy as np

# ==============================================================================
# CONFIG
# ==============================================================================
DEFAULT_JSON_PATH = "port_risk_data.json"
DEFAULT_OUTPUT_CSV = "arcgis_enrichment.csv"
S3_BUCKET = "bucket-for-xgboost"
S3_PREFIX = "fruitfly-data"
REGION = "us-west-2"

# ==============================================================================
# COUNTY → AIRPORT CODE MAPPING
# Maps each detection county to the nearest major US port airport
# that exists in Final.csv (LAX, MIA, IAH, DFW)
# ==============================================================================
COUNTY_TO_AIRPORT = {
    # California → LAX
    "LOS ANGELES COUNTY": "LAX",
    "ORANGE COUNTY": "LAX",
    "RIVERSIDE COUNTY": "LAX",
    "SAN BERNARDINO COUNTY": "LAX",
    "VENTURA COUNTY": "LAX",
    "SANTA BARBARA COUNTY": "LAX",
    "KERN COUNTY": "LAX",
    "SAN DIEGO COUNTY": "LAX",
    "ALAMEDA COUNTY": "LAX",
    "CONTRA COSTA COUNTY": "LAX",
    "SAN MATEO COUNTY": "LAX",
    "SANTA CLARA COUNTY": "LAX",
    "SONOMA COUNTY": "LAX",
    "FRESNO COUNTY": "LAX",
    "MADERA COUNTY": "LAX",
    "MERCED COUNTY": "LAX",
    "PLACER COUNTY": "LAX",
    "SACRAMENTO COUNTY": "LAX",

    # Florida → MIA
    "MIAMI-DADE COUNTY": "MIA",
    "BROWARD COUNTY": "MIA",
    "HILLSBOROUGH COUNTY": "MIA",
    "PINELLAS COUNTY": "MIA",
    "SEMINOLE COUNTY": "MIA",

    # Texas South (Rio Grande Valley) → IAH
    "CAMERON COUNTY": "IAH",
    "HIDALGO COUNTY": "IAH",
    "STARR COUNTY": "IAH",
    "WEBB COUNTY": "IAH",
    "WILLACY COUNTY": "IAH",
    "ZAPATA COUNTY": "IAH",
}

# Airports that should always exist in output even if no county maps to them
ALL_AIRPORTS = ["LAX", "MIA", "IAH", "DFW"]

# Entomological temperature thresholds
TEMP_DEAD_ZONE_F = 40
TEMP_MARGINAL_F  = 45
TEMP_OPTIMAL_HI  = 75

# Port average monthly temperatures (from temperature_suitability.csv)
PORT_TEMPS = {
    "LAX": [48, 49, 51, 54, 58, 61, 64, 65, 64, 60, 53, 48],
    "MIA": [60, 62, 65, 70, 74, 77, 78, 78, 77, 74, 69, 64],
    "IAH": [43, 47, 54, 62, 69, 74, 76, 76, 72, 62, 52, 45],
    "DFW": [37, 41, 50, 59, 66, 74, 78, 78, 70, 58, 47, 39],
}


def suitability_score(temp_f):
    """Continuous suitability: raster-style overlay."""
    if temp_f < TEMP_DEAD_ZONE_F:
        return 0.0
    elif temp_f < TEMP_MARGINAL_F:
        return 0.5 * (temp_f - TEMP_DEAD_ZONE_F) / (TEMP_MARGINAL_F - TEMP_DEAD_ZONE_F)
    elif temp_f < TEMP_OPTIMAL_HI:
        return 0.5 + 0.5 * (temp_f - TEMP_MARGINAL_F) / (TEMP_OPTIMAL_HI - TEMP_MARGINAL_F)
    else:
        return 0.9


def load_port_risk_data(json_path):
    """Load port_risk_data.json."""
    print(f"Loading {json_path}...")
    with open(json_path, "r") as f:
        data = json.load(f)
    print(f"  Loaded {len(data)} county-level records")
    return data


def map_and_aggregate(port_data):
    """
    1. Map each county → airport code
    2. Flatten to monthly rows per county
    3. Aggregate counties per airport (weighted avg for scores, sum for counts)
    """
    county_rows = []

    for port in port_data:
        county_name = port.get("id", port.get("name", "UNKNOWN"))
        airport = COUNTY_TO_AIRPORT.get(county_name.upper().strip())

        if airport is None:
            print(f"  WARNING: No airport mapping for '{county_name}', skipping")
            continue

        monthly_risk = port.get("monthlyRisk", [0] * 12)
        if len(monthly_risk) < 12:
            monthly_risk.extend([0] * (12 - len(monthly_risk)))

        species = port.get("species", {})
        pathway = port.get("pathway", {})

        for month_idx in range(12):
            county_rows.append({
                "county": county_name,
                "us_port": airport,
                "month": month_idx + 1,
                "cpri": port.get("cpri", 0),
                "monthly_risk": monthly_risk[month_idx],
                "detections_total": port.get("detections", 0),
                "routes": port.get("routes", 0),
                "risk_class": port.get("risk", "LOW"),
                "species_bdorsalis": species.get("bdorsalis", 0),
                "species_ccapitata": species.get("ccapitata", 0),
                "species_anastrepha": species.get("anastrepha", 0),
                "pathway_passenger": pathway.get("passenger", 0),
                "pathway_cargo": pathway.get("cargo", 0),
                "pathway_courier": pathway.get("courier", 0),
                "lat": port.get("lat", 0),
                "lng": port.get("lng", 0),
            })

    df_county = pd.DataFrame(county_rows)
    print(f"  County-level rows: {len(df_county)} ({df_county['county'].nunique()} counties)")

    # ---- Aggregate to airport level ----
    # For each airport + month: weighted average of scores, sum of counts
    agg_dict = {
        "cpri":               "mean",
        "monthly_risk":       "mean",
        "detections_total":   "sum",
        "routes":             "sum",
        "species_bdorsalis":  "mean",
        "species_ccapitata":  "mean",
        "species_anastrepha": "mean",
        "pathway_passenger":  "mean",
        "pathway_cargo":      "mean",
        "pathway_courier":    "mean",
        "county":             "count",  # number of counties feeding this airport
    }

    df_agg = df_county.groupby(["us_port", "month"]).agg(agg_dict).reset_index()
    df_agg.rename(columns={"county": "n_counties"}, inplace=True)

    # Round for cleanliness
    for col in ["cpri", "monthly_risk", "species_bdorsalis", "species_ccapitata",
                "species_anastrepha", "pathway_passenger", "pathway_cargo", "pathway_courier"]:
        df_agg[col] = df_agg[col].round(2)

    # Determine dominant risk class per airport-month
    risk_map = {"LOW": 0, "MEDIUM": 1, "HIGH": 2, "CRITICAL": 3}
    df_county["risk_numeric"] = df_county["risk_class"].map(risk_map).fillna(0)
    risk_agg = df_county.groupby(["us_port", "month"])["risk_numeric"].max().reset_index()
    inv_risk_map = {0: "LOW", 1: "MEDIUM", 2: "HIGH", 3: "CRITICAL"}
    risk_agg["risk_class"] = risk_agg["risk_numeric"].map(inv_risk_map)
    df_agg = df_agg.merge(risk_agg[["us_port", "month", "risk_class", "risk_numeric"]],
                          on=["us_port", "month"], how="left")

    print(f"  Aggregated to airport level: {len(df_agg)} rows ({df_agg['us_port'].nunique()} airports)")

    # ---- Add DFW with baseline values if missing ----
    existing_airports = set(df_agg["us_port"].unique())
    for apt in ALL_AIRPORTS:
        if apt not in existing_airports:
            print(f"  Adding baseline rows for {apt} (no county detections mapped)")
            for m in range(1, 13):
                df_agg = pd.concat([df_agg, pd.DataFrame([{
                    "us_port": apt,
                    "month": m,
                    "cpri": 10.0,
                    "monthly_risk": 0.0,
                    "detections_total": 0,
                    "routes": 0,
                    "species_bdorsalis": 0,
                    "species_ccapitata": 0,
                    "species_anastrepha": 0,
                    "pathway_passenger": 0,
                    "pathway_cargo": 0,
                    "pathway_courier": 0,
                    "n_counties": 0,
                    "risk_class": "LOW",
                    "risk_numeric": 0,
                }])], ignore_index=True)

    return df_agg


def add_derived_features(df):
    """Add temperature suitability and composite features."""

    # Temperature suitability per airport per month
    temps = []
    for _, row in df.iterrows():
        port_temps = PORT_TEMPS.get(row["us_port"], [55] * 12)
        temps.append(port_temps[int(row["month"]) - 1])
    df["port_temp_f"] = temps

    df["temp_suitability"] = df["port_temp_f"].apply(suitability_score)
    df["temp_viable"] = (df["port_temp_f"] >= TEMP_DEAD_ZONE_F).astype(int)

    # Temperature-weighted risk (raster overlay: risk × suitability)
    df["temp_weighted_risk"] = (df["monthly_risk"] * df["temp_suitability"]).round(2)

    # Species diversity index (inverted Herfindahl)
    df["species_diversity_idx"] = (1.0 - (
        (df["species_bdorsalis"]/100)**2 +
        (df["species_ccapitata"]/100)**2 +
        (df["species_anastrepha"]/100)**2
    )).round(4)

    # Peak season flag (Jun-Sep)
    df["peak_season"] = df["month"].isin([6, 7, 8, 9]).astype(int)
    df["seasonal_risk"] = (df["monthly_risk"] * df["peak_season"] * df["temp_suitability"]).round(2)

    # CPRI × temperature composite
    df["cpri_temp_composite"] = (df["cpri"] * df["temp_suitability"]).round(2)

    # Route risk composite
    df["route_risk_composite"] = (df["routes"] * df["monthly_risk"] / 100 * df["temp_suitability"]).round(2)

    # Risk vs annual baseline
    df["risk_vs_annual"] = (df["monthly_risk"] - df["cpri"]).round(2)

    # Log transforms
    df["log_routes"] = np.log1p(df["routes"]).round(4)
    df["log_detections"] = np.log1p(df["detections_total"]).round(4)

    # Rename for clarity in training script
    df.rename(columns={
        "cpri": "arcgis_cpri",
        "monthly_risk": "arcgis_monthly_risk",
        "detections_total": "arcgis_detections_total",
        "routes": "arcgis_routes",
        "risk_class": "arcgis_risk_class",
        "risk_numeric": "arcgis_risk_numeric",
    }, inplace=True)

    print(f"  Added derived features. Final columns: {len(df.columns)}")
    return df


def validate_output(df):
    """Sanity checks."""
    print("===== VALIDATION =====")
    print(f"Shape: {df.shape}")
    print(f"Airports: {sorted(df['us_port'].unique())}")
    print(f"Months: {sorted(df['month'].unique())}")

    dead = df[df["temp_viable"] == 0]
    print(f"Dead zone rows (temp < 40F): {len(dead)}")
    if len(dead) > 0:
        for _, r in dead.iterrows():
            print(f"  {r['us_port']} month {int(r['month'])}: {r['port_temp_f']}F -> risk={r['temp_weighted_risk']}")

    print(f"Per-airport summary:")
    for apt in sorted(df["us_port"].unique()):
        sub = df[df["us_port"] == apt]
        print(f"  {apt}: CPRI={sub['arcgis_cpri'].mean():.1f}, "
              f"counties={sub['n_counties'].max()}, "
              f"detections={sub['arcgis_detections_total'].max()}, "
              f"risk={sub['arcgis_risk_class'].iloc[0]}")

    print(f"Key stats:")
    print(df[["arcgis_cpri", "arcgis_monthly_risk", "temp_weighted_risk"]].describe().round(2).to_string())
    print("===== VALIDATION COMPLETE =====")


def upload_to_s3(csv_path, bucket, prefix, region):
    """Upload to S3."""
    try:
        import boto3
        s3 = boto3.client("s3", region_name=region)
        s3_key = f"{prefix}/{os.path.basename(csv_path)}"
        s3.upload_file(csv_path, bucket, s3_key)
        print(f"Uploaded to s3://{bucket}/{s3_key}")
        return True
    except Exception as e:
        print(f"S3 upload failed: {e}")
        print(f"  Manual: aws s3 cp {csv_path} s3://{bucket}/{prefix}/{os.path.basename(csv_path)}")
        return False


def main():
    parser = argparse.ArgumentParser(description="ArcGIS -> SageMaker bridge v2")
    parser.add_argument("--json", default=DEFAULT_JSON_PATH)
    parser.add_argument("--output", default=DEFAULT_OUTPUT_CSV)
    parser.add_argument("--upload", action="store_true")
    parser.add_argument("--s3-bucket", default=S3_BUCKET)
    parser.add_argument("--s3-prefix", default=S3_PREFIX)
    parser.add_argument("--region", default=REGION)
    args = parser.parse_args()

    print("=" * 60)
    print("ARCGIS BRIDGE v2 — County → Airport Aggregation")
    print("=" * 60)

    # Step 1: Load
    port_data = load_port_risk_data(args.json)

    # Step 2: Map counties → airports and aggregate
    df = map_and_aggregate(port_data)

    # Step 3: Add derived features
    df = add_derived_features(df)

    # Step 4: Validate
    validate_output(df)

    # Step 5: Save
    df.to_csv(args.output, index=False)
    print(f"Saved: {args.output} ({len(df)} rows x {len(df.columns)} columns)")

    # Step 6: Upload
    if args.upload:
        upload_to_s3(args.output, args.s3_bucket, args.s3_prefix, args.region)

    print(f"""
============================================================
MERGE INSTRUCTIONS FOR train_fruitfly.py
============================================================
The output uses AIRPORT CODES (LAX, MIA, IAH, DFW) matching Final.csv.

    arcgis = pd.read_csv(os.path.join(INPUT_DIR, "arcgis_enrichment.csv"))
    df = df.merge(arcgis, on=["us_port", "month"], how="left")

ArcGIS features to add to feature_cols:
    "arcgis_cpri", "arcgis_monthly_risk", "arcgis_detections_total",
    "arcgis_routes", "temp_weighted_risk", "species_diversity_idx",
    "cpri_temp_composite", "route_risk_composite", "risk_vs_annual",
    "arcgis_risk_numeric", "log_routes", "log_detections",
    "seasonal_risk", "n_counties"
============================================================
""")


if __name__ == "__main__":
    main()

