# Generated by Django 5.2.13 on 2026-04-25 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outbreaks', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='airtrafficaggregate',
            new_name='outbreaks_a_origin__d8db19_idx',
            old_name='outbreaks_a_orig_426b0d_idx',
        ),
        migrations.RenameIndex(
            model_name='airtrafficaggregate',
            new_name='outbreaks_a_state_n_b3889a_idx',
            old_name='outbreaks_a_state_1c03a6_idx',
        ),
        migrations.RenameIndex(
            model_name='detectionaggregate',
            new_name='outbreaks_d_state_n_1d4335_idx',
            old_name='outbreaks_d_state_cc71da_idx',
        ),
        migrations.RenameIndex(
            model_name='porttraffic',
            new_name='outbreaks_p_state_719354_idx',
            old_name='outbreaks_p_state_91dc97_idx',
        ),
    ]
